server:
  port: 9797

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
             - "*"
            allow-credentials: true   
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
          # COMPOSITION SERVICE #
        - id: composition-service
          uri: lb://COMPOSITION-SERVICE
          predicates:
            - Path=/oio/**
            - Method=GET, POST, PUT, DELETE, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/composition-service/(?<segment>.*), /$\{segment}

          # CHAT SERVICE #
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

          # CONTENT SERVICE #
        - id: content-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/content-service/**
            - Method=GET, POST, PUT, DELETE, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/content-service/(?<segment>.*), /$\{segment}

          # MEMBER SERVICE #
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET, POST, PUT, DELETE, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

          # PRODUCT SERVICE #
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
            - Method=GET, POST, PUT, DELETE, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

          # TRANSACTION SERVICE #
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction-service/**
            - Method=GET, POST, PUT, DELETE, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/transaction-service/(?<segment>.*), /$\{segment}
